### ISSUE TITLE
Title: Class "Filament\View\PanelsRenderHook" not found error when using BannerPlugin

### ISSUE THREAD

**Issue by afiktahirov** [kenepa/banner#12]
### What happened?

I am encountering an error when trying to use the kenepa/banner plugin with my Filament-based application. After following the installation steps, I receive the following error when I attempt to run my application:

Class "Filament\View\PanelsRenderHook" not found

`use Kenepa\Banner\BannerPlugin;
use Filament\Panel;

public function panel(Panel $panel): Panel
{
    return $panel
        ->plugins([
            BannerPlugin::make()
                ->persistsBannersInDatabase()
        ]);
}
`
`content: [
  './vendor/kenepa/banner/resources/**/*.php',
]
`
`@import '../../../../vendor/kenepa/banner/resources/css/index.css';
`
`php artisan vendor:publish --tag="banner-migrations"
php artisan migrate
`

PHP version: 8.2.12
Laravel version: 10.48.15
Filament version: v3.2.0
kenepa/banner version: 0.0.5^

### Package Version

0.0.5

### PHP Version

8.2.12

### Laravel Version

10.48.15

**Comment by Jehizkia** [comment]
I see that you are using filament 3.2.0. Try 3.2.23 and above, but preferably the latest version.

**Comment by afiktahirov** [comment]
> Thank you for reaching out. I see that you are using filament 3.2.0. Try 3.2.23 and above, but preferably the latest version.

Thank you! Now it's working fine
