### ISSUE TITLE
[Bug]: ->maxContentWidth('full') Causes BannerManagement Menus to Be Outside Visible Area

### ISSUE THREAD

**Issue by edeoliv** [kenepa/banner#14]
### What happened?

When setting the content width to full using ->maxContentWidth('full') in the PanelProvider, the Banner Management menus are rendered outside the visible area, making them inaccessible to users.

### How to reproduce the bug

1.Configure the `PanelProvider` to use `->maxContentWidth('full')`.
2.Set up the `BannerPlugin` as described below.
3.Observe that the Banner Management menus are not fully visible.
```php
BannerPlugin::make()
    ->persistsBannersInDatabase()
    ->title(__('Banner Manager'))
    ->subheading(__('Manage your banners'))
    ->navigationIcon('heroicon-o-megaphone')
    ->navigationLabel(__('Banner Management'))
    ->navigationGroup(__('Marketing'))
    ->navigationSort(1)
    ->bannerManagerAccessPermission('banner-manager');

```
![imagen](https://github.com/user-attachments/assets/f2bac57b-3da0-4a40-baab-80ceb5069519)

### Package Version

0.0.5

### PHP Version

8.3

### Laravel Version

11

**Comment by Jehizkia** [comment]
Hey,

Thank you for reporting. 

Within your project you'll need to run:

```npm run dev``` or ```npm run build```
