### ISSUE TITLE
[Bug]: Error when using Kenepa Banner plugin with Filament v3

### ISSUE THREAD

**Issue by erdalqc** [kenepa/banner#18]
### What happened?

Class "Filament\View\PanelsRenderHook" not found

i receive this error

### How to reproduce the bug

I followed your installation commands and then proceeded with the instructions under "After creating your custom theme." The banner is now visible on my webpage. However, when I click on it, I receive the following error:

Class "Filament\View\PanelsRenderHook" not found

### Package Version

0.0.6

### PHP Version

PHP 8.1.10

### Laravel Version

laravel10.10

### Which operating systems does with happen with?

Windows

### Notes

Thank you in advance for your help.

**Comment by Jehizkia** [comment]
Which Version of filament are you using?

**Comment by Jehizkia** [comment]
Please try filament 3.2.23 and above, but preferably the latest version.
