### ISSUE TITLE
[Bug]: Unable to set recurring dateTime

### ISSUE THREAD

**Issue by NathanLochala** [kenepa/banner#21]
### What happened?

In your readme, you state: 
`Banner Scheduling: Schedule your banners to be displayed at specific times or on a recurring basis.`
Which is fantastic and exactly what I need. 
When I click on the scheduling tab, I see where I can set a start time and end time, however, I fail to see any reoccurrence options. Was I misunderstanding the feature? 
My app has a maintenance period every night. I would like to set something like, everyday between this time and this time I want the banner to be displayed. Is that possible, or was I misreading what you were trying to communicate? 

### How to reproduce the bug

Click on the scheduling tab. I do not see any reoccurrence options. 

### Package Version

0.0.8

### PHP Version

8.2

### Laravel Version

11.21

### Which operating systems does with happen with?

macOS

**Comment by Jehizkia** [comment]
Thank you for reaching out!

This is a mistake on my part. That feature is still on the roadmap to schedule a banner  on a recurring basis. But I forgot to remove it from the readme file. I'll remove it for now to prevent any other misunderstandings.

**Comment by NathanLochala** [comment]
Thank you, brother! I look forward to that feature.
