### ISSUE TITLE
[Bug]: Close button appears on different row div

### ISSUE THREAD

**Issue by Stefano-Cecere** [kenepa/banner#25]
### What happened?

After creating a banner with option "banner can be closed by user" selected, the close button appears on different row div

![image](https://github.com/user-attachments/assets/0ceb3f4b-3c09-4e16-a8e6-e295c7ed06d2)

![image](https://github.com/user-attachments/assets/6af29071-b4f4-471b-af91-820bdba9bffd)

### How to reproduce the bug

1. Go to banner manager
2. Create a banner
3. Select option "banner can be closed by user"
4. See the banner with close button in different row div 

### Package Version

0.0.9

### PHP Version

8.2

### Laravel Version

11.23.5

### Which operating systems does with happen with?

Windows

**Comment by Jehizkia** [comment]
Hi thanks for reaching out.

Did you run`npm run dev`?

**Comment by Stefano-Cecere** [comment]
In the examples above I didn't run that command but I tried to run it now and I still have the same bug

**Comment by Jehizkia** [comment]
Could you please go to the banner manager page and send a screenshot of that page?

**Comment by Stefano-Cecere** [comment]
Sorry for the delay, a lot of work..
Here you go
![Screenshot 2024-10-23 112711](https://github.com/user-attachments/assets/46e449cd-3991-4ac0-bb64-1f0ced70263d)

**Comment by Jehizkia** [comment]
No problem, thanks. 

Do you use a custom theme? And have you followed all the steps of section 2 of the installation part?  
https://github.com/kenepa/banner?tab=readme-ov-file#installation

**Comment by Stefano-Cecere** [comment]
I just redid all the steps and solved it, thank you for your support!
