### ISSUE TITLE
[Bug]:  Banner management for specific roles 

### ISSUE THREAD

**Issue by koppa53** [kenepa/banner#7]
### What happened?

Is there a feature that i can set what role can access the banner manager? I tried using the shield plugin if it will automatically handles that but it does not work.

### How to reproduce the bug

 Banner management visible in other roles.

### Package Version

0.0.4

### PHP Version

8.3.3

### Laravel Version

11.10.0

### Which operating systems does with happen with?

Windows

**Comment by Jehizkia** [comment]
Thank you for the feedback! Currently working on this: https://github.com/kenepa/banner/pull/9
