### ISSUE TITLE
[Request For Feature]: Custom banner page

### ISSUE THREAD

**Issue by aeq-dev** [kenepa/banner#8]
### What happened?

Hello,
Thanks for this awesome package,
It will be very useful if you give the ability to set custom banner page in config, where we can override it for custom staff :)
Thanks  

### How to reproduce the bug

-

### Package Version

1

### PHP Version

8.2

### Laravel Version

10

**Comment by Jehizkia** [comment]
Hey, thank you for the feedback. Are you referring to the page where you can manage the banners?

**Comment by Jehizkia** [comment]
Actually you can disable the "default" banner configuration page with:

```php
BannerPlugin::make()
    ->disableBannerManager()
```

And create your own page and interact with the BannerManager faces within your custom Livewire page:

```php
use Kenepa\Banner\Facades\BannerManager;

$banners = BannerManager::getAll();
```

**Comment by aeq-dev** [comment]
Okey, thanks :)

**Comment by Jehizkia** [comment]
No problem :)
